services:
  reverse-proxy:
    image: caddy:2-alpine
    container_name: portfolio-proxy
    restart: unless-stopped
    depends_on:
      - portfolio
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  portfolio:
    image: ghcr.io/951jth/portpolio:latest
    container_name: portfolio
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOSTNAME: 0.0.0.0


volumes:
  caddy_data:
  caddy_config:
